# Generated by Django 5.1.6 on 2025-02-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
